package com.herthrone.constant;

/**
 * Created by yifengliu on 5/15/16.
 */
public enum ConstMinion {
  CHILLWIND_YETI,
  FAERIE_DRAGON,
  GNOMISH_INVENTOR,
  HEALING_TOTEM,
  IRONFUR_GRIZZLY,
  LOOT_HOARDER,
  SEARING_TOTEM,
  SENJIN_SHIELDMASTA,
  SILVER_HAND_RECRUIT,
  STONECLAW_TOTEM,
  WOLFRIDER,
  WRATH_OF_AIR_TOTEM;
}