package com.herthrone.constant;

/**
 * Created by yifengliu on 5/15/16.
 */
public enum ConstMinion {
  CHILLWIND_YETI,
  EMPEROR_COBRA,
  FAERIE_DRAGON,
  GNOMISH_INVENTOR,
  HEALING_TOTEM,
  IRONFUR_GRIZZLY,
  LOOT_HOARDER,
  OGRE_BRUTE,
  SCARLET_CRUSADER,
  SEARING_TOTEM,
  SENJIN_SHIELDMASTA,
  SILVER_HAND_RECRUIT,
  STONECLAW_TOTEM,
  WATER_ELEMENTAL,
  WINDFURY_HARPY,
  WOLFRIDER,
  WORGEN_INFILTRATOR,
  WRATH_OF_AIR_TOTEM;
}