package com.herthrone.constant;

/**
 * Created by yifengliu on 5/15/16.
 */
public enum ConstSpell {
  ANIMAL_COMPANION,
  ARCANE_EXPLOSION,
  ARCANE_INTELLECT,
  ARCANE_SHOT,
  ARMOR_UP,
  CLAW,
  DAGGER_MASTERY,
  FIRE_BLAST,
  FIRE_BALL,
  FLAMESTRIKE,
  FROSTBOLT,
  FROST_NOVA,
  HEALING_TOUCH,
  HUNTERS_MARK,
  INNERVATE,
  KILL_COMMAND,
  LESSER_HEAL,
  LIFE_TAP,
  MARK_OF_THE_WILD,
  MIRROR_IMAGE,
  MOONFIRE,
  MULTI_SHOT,
  POLYMORPH,
  REINFORCE,
  SAVAGE_ROAR,
  SHAPESHIFT,
  STARFIRE,
  STEADY_SHOT,
  SWIPE,
  TRACKING,
  TOTEMIC_CALL,
  WILD_GROWTH;
}
